[window]
dimensions = { columns = 80, lines = 24 }
padding = { x = 5, y = 5 }
opacity = 0.85

[font]
normal = { family = "CommitMono Nerd Font", style = "regular" }
size = 12

[colors.primary]
foreground = "#cbd4c1"

[colors.normal]
red = "#b0223c"
green = "#2c6d37"
yellow = "#b35a21"
blue = "#003f74"
magenta = "#b03881"
cyan = "#48629C"
white = "#cbd4c1"

[colors.bright]
red = "#c57277"
green = "#78A65A"
yellow = "#C58B5F"
blue = "#257697"
magenta = "#c7849d"
cyan = "#93b2bb"
white = "#ffffff"

[colors.search]
matches = { foreground = "#c57277", background = "#2c6d37" }

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 600
blink_timeout = 0
vi_mode_style = { shape = "Block", blinking = "Off" }

[mouse]
hide_when_typing = true
